//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHE_MVC_0._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIClass
    {
        public int cid { get; set; }
        public string name { get; set; }
        public Nullable<int> pid { get; set; }
        public bool isAbstract { get; set; }
    }
}
